# zap_to_python.zap - Minimal Zap-to-Python transpiler written in Zap
# This is a self-hosting proof-of-concept: Zap code that transpiles Zap to Python
# Usage: zap run zap_to_python.zap <input.zap> [--output <out.py>]

let args = sys_args()
let input_file = args[1]
let output_file = ""

if len(args) > 2:
  if args[2] == "--output":
    output_file = args[3]
  el:
    output_file = input_file.replace(".zap", ".py")
el:
  output_file = input_file.replace(".zap", ".py")

print("Zap to Python transpiler (self-hosting)")
print("Input:  " + input_file)
print("Output: " + output_file)

# Read the Zap source
let source = read_file(input_file)
let lines = source.split("\n")

let python_lines = []
python_lines.append("# Generated by Zap self-hosting transpiler")
python_lines.append("import math")
python_lines.append("import random")
python_lines.append("import sys")
python_lines.append("")

# Track indentation level
let indent_level = 0

for line in lines:
  let trimmed = line.trim()

  # Skip empty lines and comments
  if trimmed == "":
    python_lines.append("")
    continue
  if trimmed.startswith("//"):
    python_lines.append("  ".repeat(indent_level) + "# " + trimmed.slice(2))
    continue

  # Count leading spaces for indentation
  let spaces = 0
  for ch in line:
    if ch == " ":
      spaces = spaces + 1
    el:
      break
  indent_level = spaces / 4

  let py_line = transpile_line(trimmed, indent_level)
  if py_line != "":
    python_lines.append(py_line)

let py_code = python_lines.join("\n")

if output_file != "":
  write_file(output_file, py_code)
  print("Transpiled to: " + output_file)
el:
  print("--- Python Output ---")
  print(py_code)

# ---- Transpiler Logic ----

fn transpile_line(line, indent):
  let prefix = "    ".repeat(indent)

  # let statements
  if line.startswith("let "):
    ret transpile_let(line, prefix)

  # if statements
  if line.startswith("if ") and line.endswith(":"):
    ret transpile_if(line, prefix)

  # else / else if
  if line == "":
    ret ""
  if line.startswith("el: if "):
    let cond = extract_condition(line, "el: if")
    ret prefix + "elif " + transpile_expr(cond) + ":"
  if line == "el:":
    ret prefix + "else:"

  # while loops
  if line.startswith("while ") and line.endswith(":"):
    ret transpile_while(line, prefix)

  # for loops
  if line.startswith("for ") and line.contains(" in "):
    ret transpile_for(line, prefix)

  # fn definitions
  if line.startswith("fn "):
    ret transpile_fn(line, prefix)

  # ret
  if line.startswith("ret "):
    let expr = line.slice(4)
    ret prefix + "return " + transpile_expr(expr)

  # print
  if line.startswith("print("):
    ret transpile_print(line, prefix)

  # Function calls and assignments
  if line.contains("=") and not line.contains("==") and not line.contains("!=") and not line.contains("<=") and not line.contains(">="):
    ret transpile_assignment(line, prefix)

  # Regular expression
  ret prefix + transpile_expr(line)

fn transpile_let(line, prefix):
  # let x = expr
  let content = line.slice(4)
  let parts = content.split("=", 2)
  let name = parts[0].trim()
  let value = parts[1].trim()
  ret prefix + name + " = " + transpile_expr(value)

fn transpile_if(line, prefix):
  let cond = extract_condition(line, "if")
  ret prefix + "if " + transpile_expr(cond) + ":"

fn transpile_while(line, prefix):
  let cond = extract_condition(line, "while")
  ret prefix + "while " + transpile_expr(cond) + ":"

fn transpile_for(line, prefix):
  # for x in iterable:
  let content = line.slice(4, len(line) - 1)
  let parts = content.split(" in ")
  let var_name = parts[0].trim()
  let iterable = parts[1].trim()
  ret prefix + "for " + var_name + " in " + transpile_expr(iterable) + ":"

fn transpile_fn(line, prefix):
  # fn name(args):
  let content = line.slice(3, len(line) - 1)
  let parts = content.split("(", 2)
  let name = parts[0].trim()
  let params_str = parts[1].replace(")", "").trim()
  let params = params_str.split(",")
  let py_params = []
  for p in params:
    py_params.append(p.trim())
  ret prefix + "def " + name + "(" + py_params.join(", ") + "):"

fn transpile_print(line, prefix):
  # print(expr)
  let expr = line.slice(6, len(line) - 1)
  ret prefix + "print(" + transpile_expr(expr) + ")"

fn transpile_assignment(line, prefix):
  let parts = line.split("=", 2)
  let target = parts[0].trim()
  let value = parts[1].trim()
  ret prefix + target + " = " + transpile_expr(value)

fn transpile_expr(expr):
  # Basic expression transpilation
  # Replace Zap-specific constructs with Python equivalents

  let result = expr

  # true/false/none
  result = result.replace("true", "True")
  result = result.replace("false", "False")
  result = result.replace("none", "None")

  # String interpolation
  if result.contains("$"):
    result = transpile_string_interpolation(result)

  # .len -> len()
  if result.contains(".len"):
    result = result.replace(".len", "__len__()")
    result = "len(" + result.replace("__len__()", "") + ")"

  ret result

fn transpile_string_interpolation(s):
  # Convert "Hello $name" to f"Hello {name}"
  # And "${expr}" to f"{expr}"

  let result = s

  # Check if it's a string literal
  if result.startswith('"') and result.endswith('"'):
    let inner = result.slice(1, len(result) - 1)

    # Replace $var with {var}
    let new_inner = ""
    let i = 0
    while i < len(inner):
      if inner[i] == "$" and i + 1 < len(inner) and inner[i + 1] == "{":
        # ${expr} -> {expr}
        let end = inner.find("}", i + 2)
        if end != -1:
          let expr = inner.slice(i + 2, end)
          new_inner = new_inner + "{" + transpile_expr(expr) + "}"
          i = end + 1
        el:
          new_inner = new_inner + inner[i]
          i = i + 1
      el:
        if inner[i] == "$" and i + 1 < len(inner) and is_alpha(inner[i + 1]):
          # $var -> {var}
          let var_end = i + 1
          while var_end < len(inner) and is_alnum(inner[var_end]):
            var_end = var_end + 1
          let var_name = inner.slice(i + 1, var_end)
          new_inner = new_inner + "{" + var_name + "}"
          i = var_end
        el:
          new_inner = new_inner + inner[i]
          i = i + 1

    ret 'f"' + new_inner + '"'

  ret result

fn extract_condition(line, keyword):
  # Extract condition from "if condition:" or "while condition:"
  let content = line.slice(len(keyword))
  # Remove trailing :
  if content.endswith(":"):
    content = content.slice(0, len(content) - 1)
  ret content.trim()

fn is_alpha(ch):
  ret (ch >= "a" and ch <= "z") or (ch >= "A" and ch <= "Z") or ch == "_"

fn is_alnum(ch):
  ret is_alpha(ch) or (ch >= "0" and ch <= "9")

fn string_len(s):
  # Helper to get string length
  let count = 0
  for ch in s:
    count = count + 1
  ret count
