db_open("testdb")
db_exec("testdb", "CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT, email TEXT)")
db_exec("testdb", "INSERT INTO users (name, email) VALUES (?, ?)", ["Alice", "alice@example.com"])
db_exec("testdb", "INSERT INTO users (name, email) VALUES (?, ?)", ["Bob", "bob@example.com"])
users = db_query("testdb", "SELECT * FROM users")
print(users)
user = db_query_one("testdb", "SELECT * FROM users WHERE name = ?", ["Alice"])
print(user)
db_close("testdb")