"""Zap compile support.

This module provides a compile path for `zap compile`. It transpiles Zap source
into an executable Python wrapper and caches the compiled bytecode in `.zap_cache/`.

The cache uses a manifest file to track validity. The manifest stores:
- source hash (SHA-256 of the .zap file content)
- source mtime_ns and size
- grammar version
- output path

Cache invalidation happens automatically when any of these change.

Usage:
    zap compile main.zap              # compile + cache
    zap compile main.zap --out app.py # compile to explicit output
    zap run main.zap                  # uses cache if available
"""

from __future__ import annotations

import hashlib
import json
import os
import py_compile
import tempfile
import textwrap

from .lexer import Lexer
from .parser import Parser
from .evaluator import Evaluator
from .version import GRAMMAR_VERSION

CACHE_DIR = ".zap_cache"
MANIFEST_NAME = "manifest.json"


def transpile_to_python_source(source: str, filename: str | None = None) -> str:
    """Return Python source that executes the given Zap source."""
    filename = filename or "<zap>"
    zap_text = json.dumps(source)
    python_filename = json.dumps(filename)
    return textwrap.dedent(f"""\
        # Auto-generated Zap wrapper for {filename}
        # Do not edit this file.
        from __future__ import annotations
        import json
        import sys as _sys

        try:
            from src.lexer import Lexer
            from src.parser import Parser
            from src.evaluator import Evaluator
        except ImportError:
            try:
                from lexer import Lexer
                from parser import Parser
                from evaluator import Evaluator
            except ImportError:
                _sys.exit("zap-lang runtime not found")

        zap_source = {zap_text}
        filepath = {python_filename}

        tokens = Lexer(zap_source, filepath).tokenize()
        prog = Parser(tokens).parse()
        ev = Evaluator(current_file=filepath)
        result = ev.evaluate(prog)
        if result is not None:
            print(result)
    """)


def _write_python_source(source: str, out_path: str) -> None:
    dirpath = os.path.dirname(out_path)
    if dirpath:
        os.makedirs(dirpath, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(source)


def _source_hash(source: str) -> str:
    """Compute SHA-256 hash of source content."""
    return hashlib.sha256(source.encode("utf-8")).hexdigest()


def _cache_dir_for(filepath: str) -> str:
    """Get the cache directory for a given source file."""
    return os.path.join(os.path.dirname(os.path.abspath(filepath)), CACHE_DIR)


def _manifest_path(filepath: str) -> str:
    """Get the manifest file path for a given source file."""
    return os.path.join(_cache_dir_for(filepath), MANIFEST_NAME)


def _cache_key(source_hash: str) -> str:
    """Generate a cache key from the source hash."""
    return source_hash[:32]


def _load_manifest(filepath: str) -> dict:
    """Load the cache manifest for a source file."""
    manifest_path = _manifest_path(filepath)
    if not os.path.exists(manifest_path):
        return {}
    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def _save_manifest(filepath: str, manifest: dict) -> None:
    """Save the cache manifest for a source file."""
    cache_dir = _cache_dir_for(filepath)
    os.makedirs(cache_dir, exist_ok=True)
    manifest_path = _manifest_path(filepath)
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)


def _is_cache_valid(filepath: str, source: str) -> bool:
    """Check if the cache is valid for the given source file."""
    try:
        stat = os.stat(filepath)
    except OSError:
        return False

    manifest = _load_manifest(filepath)
    entry = manifest.get(os.path.basename(filepath), {})

    # Check all fields match
    if entry.get("source_hash") != _source_hash(source):
        return False
    if entry.get("mtime_ns") != stat.st_mtime_ns:
        return False
    if entry.get("size") != stat.st_size:
        return False
    if entry.get("grammar") != GRAMMAR_VERSION:
        return False

    # Check the cached .pyc exists
    cache_key = _cache_key(_source_hash(source))
    cached_pyc = os.path.join(_cache_dir_for(filepath), cache_key + ".pyc")
    return os.path.exists(cached_pyc)


def _get_cached_pyc(filepath: str, source: str) -> str | None:
    """Get the path to the cached .pyc file if cache is valid."""
    if not _is_cache_valid(filepath, source):
        return None
    cache_key = _cache_key(_source_hash(source))
    cached_pyc = os.path.join(_cache_dir_for(filepath), cache_key + ".pyc")
    return cached_pyc if os.path.exists(cached_pyc) else None


def _update_cache(filepath: str, source: str, pyc_path: str) -> None:
    """Update the cache with a newly compiled .pyc file."""
    try:
        stat = os.stat(filepath)
    except OSError:
        return

    cache_key = _cache_key(_source_hash(source))
    cached_pyc = os.path.join(_cache_dir_for(filepath), cache_key + ".pyc")

    # Copy the .pyc to cache
    try:
        with open(pyc_path, "rb") as src:
            with open(cached_pyc, "wb") as dst:
                dst.write(src.read())
    except OSError:
        return

    # Update manifest
    manifest = _load_manifest(filepath)
    manifest[os.path.basename(filepath)] = {
        "source_hash": _source_hash(source),
        "mtime_ns": stat.st_mtime_ns,
        "size": stat.st_size,
        "grammar": GRAMMAR_VERSION,
        "cache_key": cache_key,
    }
    _save_manifest(filepath, manifest)


def compile_to_file(source: str, filepath: str, out_path: str | None = None,
                    *, use_cache: bool = True) -> str:
    """Compile Zap source to a Python file.

    Returns the path to the compiled output.
    If out_path is None, writes to .zap_cache/<hash>.py.
    """
    cache_dir = _cache_dir_for(filepath)
    os.makedirs(cache_dir, exist_ok=True)

    if out_path is None:
        cache_key = _cache_key(_source_hash(source))
        out_path = os.path.join(cache_dir, cache_key + ".py")

    python_source = transpile_to_python_source(source, filepath)
    _write_python_source(python_source, out_path)
    return out_path


def transpile_and_exec(source: str, filepath: str, *,
                       fallback_to_interpreter: bool = True,
                       use_cache: bool = True) -> object:
    """Transpile Zap source to Python and execute it immediately.

    If use_cache is True, compiled bytecode is cached in .zap_cache/ and
    reused on subsequent runs (invalidated by mtime/size/hash changes).

    Falls back to the tree-walking interpreter if compilation fails.
    """
    # Try cache first
    if use_cache:
        cached_pyc = _get_cached_pyc(filepath, source)
        if cached_pyc:
            try:
                with open(cached_pyc, "rb") as f:
                    code = f.read()
                globals_: dict[str, object] = {
                    "__name__": "__main__",
                    "__file__": filepath,
                }
                exec(compile(code, filepath, "exec"), globals_)
                return globals_.get("result")
            except Exception:
                pass  # Cache corrupt, fall through to recompile

    python_source = transpile_to_python_source(source, filepath)
    with tempfile.TemporaryDirectory() as tmpdir:
        py_path = os.path.join(tmpdir, os.path.basename(filepath) + ".py")
        pyc_path = os.path.join(tmpdir, os.path.basename(filepath) + ".pyc")
        _write_python_source(python_source, py_path)

        try:
            py_compile.compile(py_path, cfile=pyc_path, doraise=True)
        except Exception:
            if fallback_to_interpreter:
                tokens = Lexer(source, filepath).tokenize()
                prog = Parser(tokens).parse()
                return Evaluator(current_file=filepath).evaluate(prog)
            raise

        # Update cache
        if use_cache:
            _update_cache(filepath, source, pyc_path)

        globals_: dict[str, object] = {
            "__name__": "__main__",
            "__file__": py_path,
        }
        exec(compile(python_source, py_path, "exec"), globals_)
        return globals_.get("result")


def clear_cache(filepath: str) -> int:
    """Clear the cache for a given source file. Returns number of files removed."""
    cache_dir = _cache_dir_for(filepath)
    if not os.path.exists(cache_dir):
        return 0
    count = 0
    for f in os.listdir(cache_dir):
        if f.endswith(".pyc") or f == MANIFEST_NAME:
            os.remove(os.path.join(cache_dir, f))
            count += 1
    return count
